version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "dep: "
    reviewers:
      - "gensha256"